// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOWspjNkKsTjfNgFlLiGsQhNneCMPkNuY',
    appId: '1:379961632699:web:2b240cf4ad8009796b469e',
    messagingSenderId: '379961632699',
    projectId: 'alfatir-44ad7',
    authDomain: 'alfatir-44ad7.firebaseapp.com',
    storageBucket: 'alfatir-44ad7.firebasestorage.app',
    measurementId: 'G-8NCKD9YBHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQuFLDHb3GiJJyu2brGPTMsbqgrlyp96Y',
    appId: '1:379961632699:android:f6a7018fe45be96f6b469e',
    messagingSenderId: '379961632699',
    projectId: 'alfatir-44ad7',
    storageBucket: 'alfatir-44ad7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6j3uieDX6awUL_1RbqfiWcDJmwTy6hXI',
    appId: '1:379961632699:ios:0bfb351d3c7aa0df6b469e',
    messagingSenderId: '379961632699',
    projectId: 'alfatir-44ad7',
    storageBucket: 'alfatir-44ad7.firebasestorage.app',
    iosBundleId: 'com.example.alfatirProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6j3uieDX6awUL_1RbqfiWcDJmwTy6hXI',
    appId: '1:379961632699:ios:0bfb351d3c7aa0df6b469e',
    messagingSenderId: '379961632699',
    projectId: 'alfatir-44ad7',
    storageBucket: 'alfatir-44ad7.firebasestorage.app',
    iosBundleId: 'com.example.alfatirProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOWspjNkKsTjfNgFlLiGsQhNneCMPkNuY',
    appId: '1:379961632699:web:bd51b41a9f077e9f6b469e',
    messagingSenderId: '379961632699',
    projectId: 'alfatir-44ad7',
    authDomain: 'alfatir-44ad7.firebaseapp.com',
    storageBucket: 'alfatir-44ad7.firebasestorage.app',
    measurementId: 'G-1YF1EHBL3J',
  );

}